### ISSUE TITLE
Unexpected keyword argument 'z'

### ISSUE THREAD

**Issue by nicoostendorf** [ibr-cm/ions#19]
I tried to run the heatmap example from the recipe.yaml.

```
 - cbr_heatmap: !PlottingTask
      dataset_name: "pos"
      selector: "moduleName.str.contains(r'World.node\\[5..\\].middleware.McService')"
      plot_type: "heat"

      x: "posX"
      y: "posY"
      z: "cbr"

      # column: 'v2x_rate'

      # yrange: (0, 0.8)
      # the side length of the square position bin
      bin_size: 25.

      legend: !!null
      # colormap: "gist_heat"
      colormap: "blend:white,#bb2323"
```

For me it return an error:

```
ERROR | run_recipe::root::<module> | e=TypeError("PlottingTask.__init__() got an unexpected keyword argument 'z'")
ERROR | run_recipe::root::<module> | Traceback (most recent call last):
```

**Comment by awillecke** [comment]
Hey,

it seems like the z parameter has gone missing somehow. 
I couldn't test it, but I guess the `heatplot` branch could help.

**Comment by hagau** [comment]
Thank you for reporting this @nicoostendorf. Sorry for the late response, it took a bit longer to test this out.

@awillecke Yes, that is actually all that is necessary.  I'll merge that into `main` if you don't want to create a PR.

**Comment by hagau** [comment]
Ok, I've merged the patch into `main`, the heatmap plot should work again. At least it does in my test runs.
Thanks again to both of you :slightly_smiling_face:.
